import type { 
  Employe, 
  DemandeConge, 
  DemandeDocument, 
  StatistiquesRH,
  Departement,
  Notification 
} from '@/types'

// Employés fictifs avec photos Unsplash
export const employesMock: Employe[] = [
  {
    id: '1',
    prenom: 'Marie',
    nom: 'Dubois',
    email: 'marie.dubois@entreprise.fr',
    poste: 'Directrice RH',
    departement: 'Ressources Humaines',
    dateEmbauche: '2018-03-15',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 89',
    statut: 'actif',
    soldeConges: 25,
    soldeRTT: 10,
    role: 'rh',
  },
  {
    id: '2',
    prenom: 'Thomas',
    nom: 'Martin',
    email: 'thomas.martin@entreprise.fr',
    poste: 'Développeur Senior',
    departement: 'Technologie',
    dateEmbauche: '2020-09-01',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 90',
    statut: 'actif',
    manager: '1',
    soldeConges: 18,
    soldeRTT: 8,
    role: 'employe',
  },
  {
    id: '3',
    prenom: 'Sophie',
    nom: 'Bernard',
    email: 'sophie.bernard@entreprise.fr',
    poste: 'Chef de Projet',
    departement: 'Marketing',
    dateEmbauche: '2019-06-20',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 91',
    statut: 'conge',
    manager: '1',
    soldeConges: 12,
    soldeRTT: 5,
    role: 'manager',
  },
  {
    id: '4',
    prenom: 'Lucas',
    nom: 'Petit',
    email: 'lucas.petit@entreprise.fr',
    poste: 'Designer UX',
    departement: 'Design',
    dateEmbauche: '2021-02-10',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 92',
    statut: 'actif',
    manager: '3',
    soldeConges: 22,
    soldeRTT: 9,
    role: 'employe',
  },
  {
    id: '5',
    prenom: 'Emma',
    nom: 'Leroy',
    email: 'emma.leroy@entreprise.fr',
    poste: 'Comptable',
    departement: 'Finance',
    dateEmbauche: '2017-11-05',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 93',
    statut: 'actif',
    manager: '1',
    soldeConges: 20,
    soldeRTT: 7,
    role: 'employe',
  },
  {
    id: '6',
    prenom: 'Antoine',
    nom: 'Moreau',
    email: 'antoine.moreau@entreprise.fr',
    poste: 'Commercial',
    departement: 'Ventes',
    dateEmbauche: '2022-01-15',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 94',
    statut: 'actif',
    manager: '1',
    soldeConges: 25,
    soldeRTT: 10,
    role: 'employe',
  },
  {
    id: '7',
    prenom: 'Camille',
    nom: 'Girard',
    email: 'camille.girard@entreprise.fr',
    poste: 'Assistante Administrative',
    departement: 'Administration',
    dateEmbauche: '2023-04-01',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 95',
    statut: 'actif',
    manager: '1',
    soldeConges: 25,
    soldeRTT: 10,
    role: 'employe',
  },
  {
    id: '8',
    prenom: 'Julien',
    nom: 'Roux',
    email: 'julien.roux@entreprise.fr',
    poste: 'Développeur Full Stack',
    departement: 'Technologie',
    dateEmbauche: '2021-08-20',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face',
    telephone: '01 23 45 67 96',
    statut: 'absent',
    manager: '2',
    soldeConges: 15,
    soldeRTT: 6,
    role: 'employe',
  },
]

// Demandes de congés fictives
export const demandesCongesMock: DemandeConge[] = [
  {
    id: 'c1',
    employeId: '3',
    type: 'conge_paye',
    dateDebut: '2026-04-25',
    dateFin: '2026-05-02',
    motif: 'Vacances en famille',
    statut: 'approuve',
    dateCreation: '2026-04-10',
    dateTraitement: '2026-04-12',
    nombreJours: 6,
  },
  {
    id: 'c2',
    employeId: '2',
    type: 'rtt',
    dateDebut: '2026-04-28',
    dateFin: '2026-04-28',
    statut: 'en_attente',
    dateCreation: '2026-04-18',
    nombreJours: 1,
  },
  {
    id: 'c3',
    employeId: '4',
    type: 'conge_paye',
    dateDebut: '2026-05-10',
    dateFin: '2026-05-15',
    motif: 'Mariage ami',
    statut: 'en_attente',
    dateCreation: '2026-04-15',
    nombreJours: 4,
  },
  {
    id: 'c4',
    employeId: '5',
    type: 'maladie',
    dateDebut: '2026-04-14',
    dateFin: '2026-04-16',
    motif: 'Certificat médical fourni',
    statut: 'approuve',
    dateCreation: '2026-04-14',
    dateTraitement: '2026-04-14',
    nombreJours: 3,
  },
  {
    id: 'c5',
    employeId: '6',
    type: 'exceptionnel',
    dateDebut: '2026-04-22',
    dateFin: '2026-04-22',
    motif: 'Déménagement',
    statut: 'refuse',
    dateCreation: '2026-04-08',
    dateTraitement: '2026-04-10',
    commentaireRH: 'Demande incomplète, justificatif manquant',
    nombreJours: 1,
  },
  {
    id: 'c6',
    employeId: '7',
    type: 'conge_paye',
    dateDebut: '2026-06-01',
    dateFin: '2026-06-14',
    motif: 'Vacances été',
    statut: 'en_attente',
    dateCreation: '2026-04-19',
    nombreJours: 10,
  },
  {
    id: 'c7',
    employeId: '8',
    type: 'maladie',
    dateDebut: '2026-04-20',
    dateFin: '2026-04-21',
    statut: 'approuve',
    dateCreation: '2026-04-20',
    dateTraitement: '2026-04-20',
    nombreJours: 2,
  },
]

// Demandes de documents fictives
export const demandesDocumentsMock: DemandeDocument[] = [
  {
    id: 'd1',
    employeId: '2',
    typeDocument: 'attestation_emploi',
    statut: 'en_attente',
    dateCreation: '2026-04-17',
    commentaire: 'Pour dossier location',
  },
  {
    id: 'd2',
    employeId: '5',
    typeDocument: 'fiche_paie',
    statut: 'approuve',
    dateCreation: '2026-04-10',
    dateTraitement: '2026-04-12',
    fichierUrl: '/documents/fiche-paie-emma-mars.pdf',
  },
  {
    id: 'd3',
    employeId: '4',
    typeDocument: 'certificat_travail',
    statut: 'en_attente',
    dateCreation: '2026-04-18',
  },
  {
    id: 'd4',
    employeId: '6',
    typeDocument: 'attestation_salaire',
    statut: 'approuve',
    dateCreation: '2026-04-05',
    dateTraitement: '2026-04-08',
    commentaire: 'Pour prêt immobilier',
  },
  {
    id: 'd5',
    employeId: '3',
    typeDocument: 'contrat_travail',
    statut: 'refuse',
    dateCreation: '2026-04-01',
    dateTraitement: '2026-04-03',
    commentaire: 'Document déjà fourni lors de l\'embauche',
  },
]

// Départements
export const departementsMock: Departement[] = [
  { id: 'dep1', nom: 'Ressources Humaines', responsable: '1', effectif: 3, couleur: '#E5B800' },
  { id: 'dep2', nom: 'Technologie', responsable: '2', effectif: 12, couleur: '#1a1a1a' },
  { id: 'dep3', nom: 'Marketing', responsable: '3', effectif: 8, couleur: '#666666' },
  { id: 'dep4', nom: 'Finance', responsable: '5', effectif: 5, couleur: '#D4A800' },
  { id: 'dep5', nom: 'Ventes', responsable: '6', effectif: 15, couleur: '#333333' },
  { id: 'dep6', nom: 'Design', responsable: '4', effectif: 4, couleur: '#B39800' },
  { id: 'dep7', nom: 'Administration', responsable: '7', effectif: 6, couleur: '#4d4d4d' },
]

// Statistiques
export const statistiquesMock: StatistiquesRH = {
  totalEmployes: 53,
  employesActifs: 48,
  employesEnConge: 4,
  demandesEnAttente: 4,
  tauxAbsenteisme: 3.2,
  congesApprouvesCeMois: 12,
  documentsTraitesCeMois: 28,
  evolutionEffectif: [
    { mois: 'Jan', effectif: 48 },
    { mois: 'Fév', effectif: 49 },
    { mois: 'Mar', effectif: 51 },
    { mois: 'Avr', effectif: 53 },
    { mois: 'Mai', effectif: 53 },
    { mois: 'Juin', effectif: 55 },
  ],
  repartitionDepartements: [
    { departement: 'Technologie', effectif: 12 },
    { departement: 'Ventes', effectif: 15 },
    { departement: 'Marketing', effectif: 8 },
    { departement: 'Administration', effectif: 6 },
    { departement: 'Finance', effectif: 5 },
    { departement: 'Design', effectif: 4 },
    { departement: 'RH', effectif: 3 },
  ],
  typesCongesUtilises: [
    { type: 'Congé payé', nombre: 45 },
    { type: 'RTT', nombre: 28 },
    { type: 'Maladie', nombre: 12 },
    { type: 'Exceptionnel', nombre: 5 },
  ],
}

// Notifications mock
export const notificationsMock: Notification[] = [
  {
    id: 'n1',
    titre: 'Nouvelle demande de congé',
    message: 'Thomas Martin a soumis une demande de RTT pour le 28 avril.',
    type: 'info',
    lu: false,
    dateCreation: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 min ago
  },
  {
    id: 'n2',
    titre: 'Demande approuvée',
    message: 'Votre demande de congé du 25 avril au 2 mai a été approuvée.',
    type: 'succes',
    lu: false,
    dateCreation: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
  },
  {
    id: 'n3',
    titre: 'Document disponible',
    message: 'Votre fiche de paie de mars est maintenant disponible au téléchargement.',
    type: 'info',
    lu: true,
    dateCreation: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
  },
  {
    id: 'n4',
    titre: 'Rappel: Solde de congés',
    message: 'Il vous reste 18 jours de congés à prendre avant la fin de l\'année.',
    type: 'avertissement',
    lu: true,
    dateCreation: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
  },
  {
    id: 'n5',
    titre: 'Demande de document',
    message: 'Lucas Petit a demandé un certificat de travail.',
    type: 'info',
    lu: false,
    dateCreation: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 min ago
  },
]

// Fonction utilitaire pour enrichir les demandes avec les infos employé
export function enrichirDemandesConges(demandes: DemandeConge[]): DemandeConge[] {
  return demandes.map(demande => ({
    ...demande,
    employe: employesMock.find(e => e.id === demande.employeId),
  }))
}

export function enrichirDemandesDocuments(demandes: DemandeDocument[]): DemandeDocument[] {
  return demandes.map(demande => ({
    ...demande,
    employe: employesMock.find(e => e.id === demande.employeId),
  }))
}
